#!/usr/bin/env python3
"""ETF Rating メール送信スクリプト.

`/etf-rating` スキルの Phase 3 が生成する email_payload.json を読み込み、
etf_rating_notifier.notify_etf_rating で送信する薄いラッパー。

実送信は `ETF_RATING_MAIL_ENABLED=1` 設定下でのみ実行。
未設定または `0` の場合は強制 dry-run。
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
BACKEND_DIR = SCRIPT_DIR.parent
PROJECT_ROOT = BACKEND_DIR.parent

os.environ.setdefault("APP_BASE_DIR", str(PROJECT_ROOT))
os.environ.setdefault("APP_DATA_DIR", str(PROJECT_ROOT / "data"))
db_path = PROJECT_ROOT / "data" / "etf.db"
os.environ.setdefault("DATABASE_URL", f"sqlite:///{db_path}")

sys.path.insert(0, str(BACKEND_DIR))
sys.path.insert(0, str(SCRIPT_DIR))

from base_batch import BaseBatchScript  # noqa: E402

from src.services.etf_rating_notifier import notify_etf_rating  # noqa: E402


class ETFRatingSendMailScript(BaseBatchScript):
    batch_name = "etf_rating_send_mail"
    description = "Send ETF rating result email"
    enable_batch_log = True

    def add_custom_arguments(self, parser: argparse.ArgumentParser) -> None:
        parser.add_argument(
            "--payload",
            type=str,
            required=True,
            help="Path to email_payload.json generated by /etf-rating skill",
        )

    def execute(self) -> int:
        self._start_batch_log()
        payload_path = Path(self.args.payload)
        if not payload_path.is_absolute():
            payload_path = (PROJECT_ROOT / payload_path).resolve()

        # fail-soft: payload 不在も exit 0、batch_log の status で判別
        if not payload_path.exists():
            self.logger.error("payload not found: %s", payload_path)
            self._finish_batch_log(
                success=False,
                error_message=f"payload not found: {payload_path}",
            )
            return 0

        try:
            ok = notify_etf_rating(payload_path, dry_run=self.args.dry_run)
        except Exception as exc:  # noqa: BLE001 — fail-soft as final guard
            self.logger.error("notify_etf_rating raised: %s", exc, exc_info=True)
            self._finish_batch_log(success=False, error_message=str(exc))
            return 0  # fail-soft: cron を止めない

        # dry-run および環境変数未設定での skip は成功扱い（exit 0）
        # SMTP 失敗のみ failed として記録するが exit code は 0（cron を止めない）
        if not ok and not self.args.dry_run:
            enabled = os.environ.get("ETF_RATING_MAIL_ENABLED", "0") == "1"
            if enabled:
                self._finish_batch_log(success=False, error_message="email send failed")
                return 0  # fail-soft: cron を止めない
        self._finish_batch_log(success=True)
        return 0


if __name__ == "__main__":
    sys.exit(ETFRatingSendMailScript().run())
